title: Sida Lin's Homepage
page-top-title: Sida Lin
top-section-bg-text: Deep Research on LLMs
home-subtitle: Sida Lin&ensp;|&ensp;林思达
copyright-text: '&copy; Sida Lin 2023-2025. All Rights Reserved.'
